services:
  - type: web
    name: emily-http
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app --bind 0.0.0.0:$PORT"

  - type: web
    name: emily-stream
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn rt_stream:app --host 0.0.0.0 --port $PORT"
